# Use the official Nginx base image
FROM nginx:latest

# Copy the HTML file to the default Nginx public directory
COPY index.html /usr/share/nginx/html/

COPY ICCS_Video_Crop.mp4 /usr/share/nginx/html/

EXPOSE 80