apiVersion: v1
kind: Namespace
metadata:
  name: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: nginx
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: enriquelluesma/nginx-video:latest
        ports:
        - containerPort: 80
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: service
                operator: In
                values:
                - iccsns
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - ubuntu-6-9
          - weight: 1
            preference:
              matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - ubuntu-6-11
          - weight: 1
            preference:
              matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - ubuntu-8-7
          - weight: 1
            preference:
              matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - ubuntu-8-15
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - nginx
            topologyKey: "kubernetes.io/hostname"
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: nginx
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
    - name: grpc
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30788

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-core-deployment
  namespace: nginx
  labels:
    app: nginx-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-core
  template:
    metadata:
      labels:
        app: nginx-core
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
      nodeName: ubuntu-10-11
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-core-service
  namespace: nginx
spec:
  selector:
    app: nginx-core
  type: NodePort
  ports:
    - name: grpc
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30789
